function g = classify_replay_landing_takeoff_other(seqs,thr)
arguments
    seqs
    thr = 0.05
end

%     near_balls_TF = [seqs.start_pos_norm] < thr | [seqs.start_pos_norm] > (1-thr) | ...
%                     [seqs.end_pos_norm] < thr   | [seqs.end_pos_norm] > (1-thr) ;
    
    landing_TF = (~[seqs.forward] & (  ([seqs.start_pos_norm] < thr     & [seqs.state_direction]==-1) | ...
                                       ([seqs.start_pos_norm] > (1-thr) & [seqs.state_direction]== 1) ) )...
                 | ...
                 ( [seqs.forward] & (  ([seqs.end_pos_norm]   < thr     & [seqs.state_direction]==-1) | ...
                                       ([seqs.end_pos_norm]   > (1-thr) & [seqs.state_direction]== 1) ) );
    
    takeoff_TF = (~[seqs.forward] & (  ([seqs.end_pos_norm] < thr     & [seqs.state_direction]== 1) | ...
                                       ([seqs.end_pos_norm] > (1-thr) & [seqs.state_direction]==-1) ) )...
                 | ...
                 ( [seqs.forward] & (  ([seqs.start_pos_norm]   < thr     & [seqs.state_direction]== 1) | ...
                                       ([seqs.start_pos_norm]   > (1-thr) & [seqs.state_direction]==-1) ) );
    g = zeros(size(seqs));
    g(landing_TF) = 1;
    g(takeoff_TF) = 2;
    g = categorical(g,[1 2 0],["Landing","Takeoff","Mid-air"])';
end